2025-07-31 10:05:25,470 - src.main - [31mERROR[0m - main.py:66 - lifespan - 系统启动失败: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
2025-07-31 10:06:30,219 - src.core.nlu_engine - [31mERROR[0m - nlu_engine.py:82 - acall - LLM异步调用异常: 
2025-07-31 10:16:35,201 - src.core.nlu_engine - [31mERROR[0m - nlu_engine.py:82 - acall - LLM异步调用异常: 
2025-07-31 10:17:13,201 - src.core.nlu_engine - [31mERROR[0m - nlu_engine.py:82 - acall - LLM异步调用异常: 
2025-07-31 10:17:13,202 - src.core.nlu_engine - [31mERROR[0m - nlu_engine.py:450 - _parse_llm_response - LLM响应JSON解析失败: Expecting value: line 1 column 1 (char 0), 响应: Error: 
2025-07-31 10:17:44,201 - src.core.nlu_engine - [31mERROR[0m - nlu_engine.py:82 - acall - LLM异步调用异常: 
2025-07-31 10:18:15,200 - src.core.nlu_engine - [31mERROR[0m - nlu_engine.py:82 - acall - LLM异步调用异常: 
2025-07-31 10:18:15,201 - src.core.nlu_engine - [31mERROR[0m - nlu_engine.py:1548 - _parse_slots_response - 槽位响应JSON解析失败: Expecting value: line 1 column 1 (char 0), 响应: Error: 
2025-07-31 11:10:39,152 - src.core.nlu_engine - [31mERROR[0m - nlu_engine.py:82 - acall - LLM异步调用异常: 
